language: node_js
node_js:
  - "12"
deploy_service_job: &DEPLOY_SERVICE_JOB
  cache:
    directories:
      - node_modules
      - ${SERVICE_PATH}/node_modules
install:
    - npm install -g serverless
    - travis_retry npm install
    - cd ${SERVICE_PATH}
    - travis_retry npm install
    - cd -
before_script:
    - export NODE_OPTIONS=--max_old_space_size=8192
script:
    - cd ${SERVICE_PATH}
    - serverless deploy -v --stage ${STAGE_NAME} --region ${AWS_REGION}
    - cd -
environments:
    - &PRODUCTION_ENV
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_PROD}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_PROD}
    - &DEVELOPMENT_ENV
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_DEV}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_DEV}
jobs:
  include:
    # develop branch deploys to the 'dev' stage
    - <<: *DEPLOY_SERVICE_JOB
      name: "DEV: Deploy API to AWS"
      if: type = push AND branch = dev
      env:
        - SERVICE_PATH="backend"
        - STAGE_NAME=dev
        - AWS_REGION=eu-central-1
        - *DEVELOPMENT_ENV
    # master branch deploys to the 'prod' stage
    - <<: *DEPLOY_SERVICE_JOB
      name: "PROD: Deploy API to AWS"
      if: type = push AND branch = master
      env:
        - SERVICE_PATH="backend"
        - STAGE_NAME=prod
        - AWS_REGION=eu-central-1
        - *PRODUCTION_ENV
